if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(ARCHITECTURE "x64")
else()
    set(ARCHITECTURE "x86")
endif()

if(MSVC)
    set(COMPILER_TYPE "MSVC")
elseif(CMAKE_COMPILER_IS_GNUCXX)
    if (WIN32)
        set(COMPILER_TYPE "MinGW")
    elseif(UNIX)
        set(COMPILER_TYPE "Unix GNU")
    endif()
elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    if (WIN32)
        set(COMPILER_TYPE "Clang MSVC")
    elseif(UNIX)
        set(COMPILER_TYPE "Clang Unix")
    endif()
else()
    set(COMPILER_TYPE "Unknown")
    message(WARNING "Unknown: ${CMAKE_CXX_COMPILER_ID}")
endif()

message(STATUS "CMAKE_SYSTEM_NAME:                      ${CMAKE_SYSTEM_NAME}")
message(STATUS "CMAKE_SYSTEM_PROCESSOR:                 ${CMAKE_SYSTEM_PROCESSOR}")

message(STATUS "COMPILER_TYPE:                          ${COMPILER_TYPE}")
message(STATUS "CMAKE_C_COMPILER:                       ${CMAKE_C_COMPILER}")
message(STATUS "CMAKE_C_COMPILER_ID:                    ${CMAKE_C_COMPILER_ID}")
message(STATUS "CMAKE_C_COMPILER_VERSION:               ${CMAKE_C_COMPILER_VERSION}")
message(STATUS "CMAKE_C_COMPILER_FRONTEND_VARIANT:      ${CMAKE_C_COMPILER_FRONTEND_VARIANT}")
message(STATUS "CMAKE_CXX_COMPILER:                     ${CMAKE_CXX_COMPILER}")
message(STATUS "CMAKE_CXX_COMPILER_ID:                  ${CMAKE_CXX_COMPILER_ID}")
message(STATUS "CMAKE_CXX_COMPILER_VERSION:             ${CMAKE_CXX_COMPILER_VERSION}")
message(STATUS "CMAKE_CXX_COMPILER_FRONTEND_VARIANT:    ${CMAKE_CXX_COMPILER_FRONTEND_VARIANT}")
 

message(STATUS "CMAKE_SIZEOF_VOID_P:                    ${CMAKE_SIZEOF_VOID_P}")
message(STATUS "ARCHITECTURE:                           ${ARCHITECTURE}")

message(STATUS "CMAKE_BUILD_TYPE:                       ${CMAKE_BUILD_TYPE}")
message(STATUS "PROBLEM_PREFIX:                         ${PROBLEM_PREFIX}")
message(STATUS "CMAKE_INSTALL_PREFIX                    ${CMAKE_INSTALL_PREFIX}")
