set(GOOGLE_TEST_PATH ${CMAKE_SOURCE_DIR}/third_lib/google_test)
set(GOOGLE_TEST_INCLUDE_PATH ${GOOGLE_TEST_PATH}/include)
set(GOOGLE_TEST_LIBRARY_PATH ${GOOGLE_TEST_PATH}/lib/${CMAKE_SYSTEM_NAME})
