set(GOOGLE_TEST_PATH ${CMAKE_SOURCE_DIR}/third_lib/google_test)
set(GOOGLE_TEST_INCLUDE_PATH ${GOOGLE_TEST_PATH}/include)

if (${CMAKE_SYSTEM_NAME} STREQUAL "Windows")
    if (MSVC)
        set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)
    endif()
    if(MINGW)
        set(GOOGLE_TEST_LIBRARY_PATH ${GOOGLE_TEST_PATH}/lib/${CMAKE_SYSTEM_NAME}/mingw)
    else()
        set(GOOGLE_TEST_LIBRARY_PATH ${GOOGLE_TEST_PATH}/lib/${CMAKE_SYSTEM_NAME}/${CMAKE_PRESET})
    endif()
else()
    set(GOOGLE_TEST_LIBRARY_PATH ${GOOGLE_TEST_PATH}/lib/${CMAKE_SYSTEM_NAME})
endif()

message(STATUS "GOOGLE_TEST_INCLUDE_PATH:               ${GOOGLE_TEST_PATH}/include")
message(STATUS "GOOGLE_TEST_LIBRARY_PATH:               ${GOOGLE_TEST_LIBRARY_PATH}")

set(MOCKCPP_PATH ${CMAKE_SOURCE_DIR}/third_lib/mockcpp)
set(MOCKCPP_INCLUDE_PATH ${MOCKCPP_PATH}/include)
set(MOCKCPP_LIBRARY_PATH ${MOCKCPP_PATH}/lib/${CMAKE_SYSTEM_NAME})
